<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0</TargetFrameworks>
    <AssemblyVersion>2.0.0.28</AssemblyVersion>
    <FileVersion>2.0.0.28</FileVersion>
    <CopyLocalLockFileAssemblies>True</CopyLocalLockFileAssemblies>
    <IncludeSourceRevisionInInformationalVersion>true</IncludeSourceRevisionInInformationalVersion>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Tokenizer\win_x64\libsimple.so" />
    <None Remove="Tokenizer\linux_x64\libsimple.so" />
    <None Remove="Tokenizer\linux_arm64\libsimple.so" />
    <None Remove="Tokenizer\osx_universal\libsimple.so" />
    <None Remove="Web\Resources\strmassistant.js" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\thumb.png" />
    <EmbeddedResource Include="Tokenizer\win_x64\libsimple.so" />
    <EmbeddedResource Include="Tokenizer\linux_x64\libsimple.so" />
    <EmbeddedResource Include="Tokenizer\linux_arm64\libsimple.so" />
    <EmbeddedResource Include="Tokenizer\osx_universal\libsimple.so" />
    <EmbeddedResource Include="Web\Resources\strmassistant.js" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ILRepack" Version="2.0.44">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Lib.Harmony" Version="2.4.0" />
    <PackageReference Include="mediabrowser.server.core" Version="4.8.5" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Resource.Embedder" Version="2.2.0" />
    <PackageReference Include="SQLitePCL.pretty.core" Version="1.2.2" />
    <PackageReference Include="ToolGood.Words" Version="3.1.0.2" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="..\libs\publicized\*.dll">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.zh-hant.resx">
      <DependentUpon>Resources.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.zh.resx">
      <DependentUpon>Resources.resx</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="$(ILRepack) /out:%25AppData%25\Emby-Server\programdata\plugins\$(TargetFileName) $(TargetPath) $(TargetDir)0Harmony.dll $(TargetDir)ToolGood.Words.dll /lib:$(TargetDir)" />
  </Target>
</Project>
